name: 'Code Reviewer Agent'
description: 'AI-powered code reviews and issue labelling'
author: 'Abhishek Ranjan'

inputs:
  gemini_api_key:
    description: 'Gemini API Key (obtained from https://aistudio.google.com/app/apikey)'
    required: true

  github_token:
    description: 'GitHub Token (automatically provided by GitHub Actions)'
    required: true
    default: ${{ github.token }}

  exclude_extensions:
    description: 'File extensions to exclude (comma-separated)'
    required: false
    default: '.md,.txt,.toml,.yml,.yaml,.json,.csv,.xml,.html,.css,.js,.ts,.jsx,.tsx'

  script_command:
    description: 'The command to pass to the code_review.py script (e.g., label_issue, review_pr)'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.script_command }}

  env:
    GEMINI_API_KEY: ${{ inputs.gemini_api_key }}
    GITHUB_TOKEN: ${{ inputs.github_token }}
    EXCLUDE_EXTENSIONS: ${{ inputs.exclude_extensions }}

branding:
  icon: 'shield'
  color: 'purple'