name: 'Code Reviewer Agent'
description: 'AI-powered code reviews and issue labelling'
author: 'Abhishek Ranjan'

inputs:
  gemini_api_key:
    description: 'Gemini API Key (obtained from https://aistudio.google.com/app/apikey)'
    required: true

  github_token:
    description: 'GitHub Token (automatically provided by GitHub Actions)'
    required: true
    default: ${{ github.token }}

  exclude_extensions:
    description: 'File extensions to exclude (comma-separated)'
    required: false

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    GEMINI_API_KEY: ${{ inputs.gemini_api_key }}
    GITHUB_TOKEN: ${{ inputs.github_token }}
    EXCLUDE_EXTENSIONS: ${{ inputs.exclude_extensions }}

branding:
  icon: 'shield'
  color: 'purple'